resources:
- repo: self
jobs:
- job: PRBuild
  condition: succeeded()
  strategy:
    maxParallel: 2
    matrix:
      'NodeJs 8':
        NodeVersion: 8
      'NodeJs 10':
        NodeVersion: 10
  steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
  - script: 'node common\scripts\install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
  - script: 'node common\scripts\install-run-rush.js check'
    displayName: 'Rush Check'
  - script: 'node common\scripts\install-run-rush.js install'
    displayName: 'rush install'
  - script: 'node common\scripts\install-run-rush.js rebuild --verbose --production'
    displayName: 'Rush Rebuild'
