resources:
- repo: self
variables:
  NodeVersion: 10
steps:
- checkout: self
- template: templates/build.yaml
- task: PublishBuildArtifacts@1
  displayName: 'Publish Playground Artifacts'
  inputs:
    PathtoPublish: playground/dist
    ArtifactName: playground
